export const studies = [
  {
    nivel: "second",
    titulo: "Facultad de Ingeniería",
    institucion: "UdelaR",
    año: "2021 - Presente",
    detalles: ["Lógica", "Programación 1 & 2", "Mat. Discreta 1", "GAL 1 & GAL 2", "CDIV & CDIVV"],
    description: "Carrera universitaria con enfoque en pensamiento lógico, estructuras matemáticas y fundamentos de programación estructurada.",
    certification: "/assets/img/certificados/Facultad_de_Ingeniería_(Uruguay).jpg",
    link_name: "Descargar escolaridad",
    link_href: "#",
  },
  {
    nivel: "second",
    titulo: "Front-End React Dev.",
    institucion: "Coderhouse",
    año: "2024",
    detalles: ["React JS", "Firebase"],
    certification: "/assets/img/certificados/66205fe55deea300199bad26.png",
    description: "Formación en desarrollo de interfaces modernas con React y conexión a bases de datos en tiempo real con Firebase. Proyecto final: una app funcional.",
  },
  {
    nivel: "second",
    titulo: "Photoshop e Illustrator",
    institucion: "Coderhouse",
    año: "2024",
    detalles: ["Adobe Photoshop", "Adobe Illustrator"],
    certification: "/assets/img/certificados/66205fe55deea300199bad26.png",
    description: "Curso intensivo de diseño gráfico con enfoque en herramientas Adobe. Aprendí a crear piezas visuales impactantes y a manipular imágenes con precisión.",
  },
  {
    nivel: "second",
    titulo: "JS for Web Developing",
    institucion: "Coderhouse",
    año: "2023",
    detalles: ["JavaScript"],
    certification: "/assets/img/certificados/658f15169a6ff76e6195c7c1.png",
    description: "Fundamentos sólidos en JavaScript, trabajando con DOM, eventos, funciones y asincronía. Ejercicios prácticos cada semana.",
  },
  {
    nivel: "second",
    titulo: "Web Developing",
    institucion: "Coderhouse",
    año: "2023",
    detalles: ["Bootstrap", "SCSS", "CSS3", "HTML5"],
    certification: "/assets/img/certificados/6500b31b98ed28448d7c031e.png",
    description: "Curso orientado a diseño responsive y buenas prácticas en maquetado web. Dominio de preprocesadores y frameworks modernos.",
  },
  {
    nivel: "second",
    titulo: "Jóvenes a Programar",
    institucion: "Plan Ceibal",
    año: "2021",
    detalles: ["Genexus Core 17", "SQL", "Competencias Transversales"],
    certification: "/assets/img/certificados/GeneXus17JuniorAnalyst-1.png",
    description: "Primer acercamiento al mundo IT, con herramientas low-code como GeneXus y conceptos de base de datos. También se trabajaron habilidades blandas.",
  },
  {
    nivel: "first",
    titulo: "Bachillerato Físico-Matemático",
    description: "Formación secundaria con fuerte énfasis en matemáticas, física y razonamiento lógico. Base ideal para carreras científicas o tecnológicas.",
  },
];
